name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker
        uses: crazy-max/ghaction-setup-docker@v3
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }
      - name: Generate Dockerfile
        run: |
          echo -e "FROM ubuntu:20.04\nRUN apt-get update && apt-get install -y curl" > Dockerfile
          ls
          pwd
      - name: Download Qscanner
        run: |
          QSCANNER_URL=$(curl $proxy -s https://www.qualys.com/downloads/qscanner/ | grep -ai "gen_cask_artifacts" | sed 's/^.*https/https/' | sed 's/".*//')
          wget $QSCANNER_URL
          ls -ltr
          pwd
          sudo bash $(pwd)/download_qscanner.sh
      - name: Docker version
        run: docker info
      - name: Build Docker image
        run: |
          docker buildx create --use
          docker buildx inspect
          docker buildx build --file /home/runner/work/dockerimage/dockerimage/Dockerfile --platform linux/amd64,linux/arm64 -t crmtestimage:multiid --load .
      - name: List docker images
        run: docker images
      - name: docker inspect
        run: |
         image_sha=$(docker inspect -f '{{.Id}}' crmtestimage:multiid)
         echo "Image SHA: $image_sha"
         docker history $image_sha
      - name: Qscanner token
        run: |
          export QUALYS_ACCESS_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJxdWF5czNiazEiLCJpc3MiOiJxYXMiLCJwb3J0YWxVc2VySWQiOjY0Mjk1MzEsInNlY3JldElkIjoiZDM3MTk1ZDYtYWIyYi00ZjRiLWJhMjEtNjM5YzBjOWUwNTdlIiwicXdlYlVzZXJJZCI6NTA3OTg1NiwiYXVkIjoicWFzIiwiY3VzdG9tZXJJZCI6NTE5ODY4LCJ1c2VyVXVpZCI6ImQ4MDRhMmZhLWQ5MTItNWY0ZC04MjY2LTRiZGZmZWRjYWE5YSIsInN1YnNjcmlwdGlvblV1aWQiOiI0ZTRiNTYyMy0xZjVjLWZiODAtODNhYS0xZmU1NzA0Zjk5MTEiLCJleHAiOjE3MzI3NDQzMzQsInN1YnNjcmlwdGlvbklkIjo0OTIyNjUzLCJ0b2tlblR5cGUiOiJzdWJzY3JpcHRpb24iLCJpYXQiOjE3MDEyMDgzMzQsImp0aSI6ImNhZmE5ZDMwLWIwMmMtNDZhZS05MGRjLWJmMmI3MGY1NTY0NyJ9.0UPBdsQnAgSPgsm7oxgTDFUBaEfCw-Cj0caig_wOs4hF9clcaBs2463ZvAaUo9wj82LHN4WWIVhLaCD_3SWmOw
          echo $QUALYS_ACCESS_TOKEN
      - name: Image scan through Qscanner
        run: |
         imagesha=$(docker inspect -f '{{.Id}}' crmtestimage:multiid)
         echo "image id: $imagesha"
         sudo $(pwd)/qscanner image $imagesha --gateway-url https://gateway.qg3.apps.qualys.com//cms/cli/v1.0 --customer-id 4e4b5623-1f5c-fb80-83aa-1fe5704f9911 --skip-verify-tls=true --access-token eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJxdWF5czNiazEiLCJpc3MiOiJxYXMiLCJwb3J0YWxVc2VySWQiOjY0Mjk1MzEsInNlY3JldElkIjoiZDM3MTk1ZDYtYWIyYi00ZjRiLWJhMjEtNjM5YzBjOWUwNTdlIiwicXdlYlVzZXJJZCI6NTA3OTg1NiwiYXVkIjoicWFzIiwiY3VzdG9tZXJJZCI6NTE5ODY4LCJ1c2VyVXVpZCI6ImQ4MDRhMmZhLWQ5MTItNWY0ZC04MjY2LTRiZGZmZWRjYWE5YSIsInN1YnNjcmlwdGlvblV1aWQiOiI0ZTRiNTYyMy0xZjVjLWZiODAtODNhYS0xZmU1NzA0Zjk5MTEiLCJleHAiOjE3MzI3NDQzMzQsInN1YnNjcmlwdGlvbklkIjo0OTIyNjUzLCJ0b2tlblR5cGUiOiJzdWJzY3JpcHRpb24iLCJpYXQiOjE3MDEyMDgzMzQsImp0aSI6ImNhZmE5ZDMwLWIwMmMtNDZhZS05MGRjLWJmMmI3MGY1NTY0NyJ9.0UPBdsQnAgSPgsm7oxgTDFUBaEfCw-Cj0caig_wOs4hF9clcaBs2463ZvAaUo9wj82LHN4WWIVhLaCD_3SWmOw
