name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Download Qscanner
      run: |
        QSCANNER_URL=$(curl $proxy -s https://www.qualys.com/downloads/qscanner/ | grep -ai "gen_cask_artifacts" | sed 's/^.*https/https/' | sed 's/".*//')
        wget $QSCANNER_URL
         ls -ltr
    - name: Build Docker image
      run: |
        docker buildx create --use
        docker buildx inspect
        docker buildx build --platform linux/amd64,linux/arm64 -t testqacrm:imagestest .
    - name: List Docker images
      run: docker images
