name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker
        uses: crazy-max/ghaction-setup-docker@v3
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }
      - name: Generate Dockerfile
        run: |
          echo "FROM ubuntu:16.04\nRUN apt-get update && apt-get install -y curl" > Dockerfile
          ls
          pwd
      - name: Download Qscanner
        run: |
          QSCANNER_URL=$(curl $proxy -s https://www.qualys.com/downloads/qscanner/ | grep -ai "gen_cask_artifacts" | sed 's/^.*https/https/' | sed 's/".*//')
          wget $QSCANNER_URL
          ls -ltr
      - name: Docker version
        run: docker info
      - name: Build Docker image
        run: |
          docker buildx create --use
          docker buildx inspect
          docker buildx build --file /home/runner/work/dockerimage/dockerimage/Dockerfile --platform linux/amd64,linux/arm64 -t crmtestimage:multiid --load .
      - name: List docker iamges
        run: docker images
