name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker
        uses: crazy-max/ghaction-setup-docker@v3
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Download Qscanner
        run: |
          QSCANNER_URL=$(curl $proxy -s https://www.qualys.com/downloads/qscanner/ | grep -ai "gen_cask_artifacts" | sed 's/^.*https/https/' | sed 's/".*//')
          wget $QSCANNER_URL
          ls -ltr
          ./download_qscanner.sh
      - name: Build Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t crmtestimage:multiid --load.
      - name: List docker iamges
        run: docker images
